import { VehicleModel, Product, Review } from './types';

export const VEHICLES: VehicleModel[] = [
  // Bikes
  { id: 'b1', type: 'Bike', brand: 'Honda', model: 'CD 70', years: Array.from({ length: 24 }, (_, i) => 2000 + i) },
  { id: 'b2', type: 'Bike', brand: 'Honda', model: 'CG 125', years: Array.from({ length: 24 }, (_, i) => 2000 + i) },
  { id: 'b3', type: 'Bike', brand: 'Yamaha', model: 'YBR 125', years: Array.from({ length: 10 }, (_, i) => 2015 + i) },
  { id: 'b4', type: 'Bike', brand: 'Suzuki Pakistan', model: 'GS 150', years: Array.from({ length: 15 }, (_, i) => 2010 + i) },
  { id: 'b5', type: 'Bike', brand: 'Suzuki Pakistan', model: 'GR 150', years: Array.from({ length: 8 }, (_, i) => 2017 + i) },
  { id: 'b6', type: 'Bike', brand: 'United', model: 'US 70', years: Array.from({ length: 15 }, (_, i) => 2010 + i) },
  
  // Cars
  { id: 'c1', type: 'Car', brand: 'Toyota', model: 'Corolla', years: Array.from({ length: 24 }, (_, i) => 2000 + i) },
  { id: 'c2', type: 'Car', brand: 'Honda', model: 'Civic', years: Array.from({ length: 24 }, (_, i) => 2000 + i) },
  { id: 'c3', type: 'Car', brand: 'Suzuki', model: 'Alto', years: Array.from({ length: 6 }, (_, i) => 2019 + i) },
  { id: 'c4', type: 'Car', brand: 'Suzuki', model: 'Cultus', years: Array.from({ length: 10 }, (_, i) => 2015 + i) },
  { id: 'c5', type: 'Car', brand: 'Kia', model: 'Sportage', years: Array.from({ length: 6 }, (_, i) => 2019 + i) },
  { id: 'c6', type: 'Car', brand: 'Hyundai', model: 'Tucson', years: Array.from({ length: 5 }, (_, i) => 2020 + i) },
];

export const CATEGORIES = [
  { name: 'LED & LIGHTNING', image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800' },
  { name: 'MODIFICATIONS', image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800' },
  { name: 'EXTERIOR', image: 'https://images.unsplash.com/photo-1594976614436-ecf130b050cf?auto=format&fit=crop&q=80&w=800' },
  { name: 'INTERIOR', image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800' },
  { name: 'PERFORMANCE', image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800' },
  { name: 'GADGETS', image: 'https://images.unsplash.com/photo-1526733169359-ab114227543a?auto=format&fit=crop&q=80&w=800' },
  { name: 'CAR CARE', image: 'https://images.unsplash.com/photo-1520333789090-1afc82db536a?auto=format&fit=crop&q=80&w=800' },
  { name: 'WHEEL & RIMS', image: 'https://images.unsplash.com/photo-1611095777215-99bb5c083bc3?auto=format&fit=crop&q=80&w=800' },
  { name: 'SECURITY GADGETS', image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800' },
  { name: 'CAR MATS', image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Universal Motorcycle Running Style Indicators (White DRL Pair)',
    price: 1450,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Dynamic flowing LED indicators with built-in White DRL. High visibility and modern aesthetic for any motorcycle.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'], models: ['CG 125', 'YBR 125', 'GS 150'], years: [2010, 2024] },
    rating: 4.8,
    reviewCount: 421,
    featured: true
  },
  {
    id: 'p2',
    name: 'Bullet Style Retro Indicators (Yellow Pair)',
    price: 950,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Classic chrome-finished bullet indicators with bright amber lighting. Perfect for classic and retro bike builds.',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda'], models: ['CD 70', 'CG 125'], years: [2000, 2024] },
    rating: 4.7,
    reviewCount: 128,
    featured: true
  },
  {
    id: 'p3',
    name: 'Police Emergency Flasher Lights (Red/Blue 12V)',
    price: 1800,
    type: 'Universal',
    category: 'LED & LIGHTNING',
    description: 'High-intensity LED strobe lights for emergency services or authorized use. Durable, waterproof housing.',
    image: 'https://images.unsplash.com/photo-1557597774-9d2739f05a76?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki'], years: [2015, 2024] },
    rating: 4.9,
    reviewCount: 88
  },
  {
    id: 'p41',
    name: 'Bike Indicator Slide Arrow Running Style with Lava DRL White & Yellow',
    price: 1350,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Arrow-shaped indicators with running yellow light and white Lava DRL. 2 Pcs Set.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha'], models: ['CG 125', 'YBR 125'], years: [2010, 2024] },
    rating: 4.8,
    reviewCount: 64
  },
  {
    id: 'p4',
    name: 'HJG Owl Shape Dual-Fog Lights',
    price: 3800,
    type: 'Universal',
    category: 'LED & LIGHTNING',
    description: 'Powerful dual-lens fog lights for extreme visibility. Includes high/low beam and yellow/white color switching.',
    image: 'https://images.unsplash.com/photo-1594976614436-ecf130b050cf?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Suzuki Pakistan', 'Toyota', 'Kia'], years: [2010, 2024] },
    rating: 5.0,
    reviewCount: 156,
    featured: true
  },
  {
    id: 'p5',
    name: '7D Diamond Stitch Custom Floor Mats (Full Set)',
    price: 11500,
    type: 'Car',
    category: 'INTERIOR',
    description: 'Premium custom-fit mats with luxury diamond stitching. Water-resistant, dust-proof, and easy to clean.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki'], models: ['Civic', 'Corolla', 'Alto'], years: [2015, 2024] },
    rating: 4.9,
    reviewCount: 234,
    featured: true
  },
  {
    id: 'p6',
    name: '10.1 inch Android Multimedia IPS Navigation Panel',
    price: 19500,
    type: 'Car',
    category: 'GADGETS',
    description: 'Upgrade your vehicle dashboard with a high-definition Android system. Supports GPS, WiFi, and Bluetooth.',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Toyota', 'Honda', 'Suzuki'], models: ['Corolla', 'Civic', 'WagonR'], years: [2014, 2024] },
    rating: 4.7,
    reviewCount: 92
  },
  {
    id: 'p7',
    name: 'LED Headlight Upgrade Kit H4 (6000K Crystal White)',
    price: 5200,
    type: 'Universal',
    category: 'LED & LIGHTNING',
    description: 'Replace dim halogens with ultra-bright 6000K LED bulbs. Instant on, superior beam pattern, and efficient cooling.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Yamaha'], years: [2008, 2024] },
    rating: 4.8,
    reviewCount: 567
  },
  {
    id: 'p8',
    name: 'Panther Trekker Dual-Purpose Rear Tire (3.00-17)',
    price: 6800,
    type: 'Bike',
    category: 'PERFORMANCE',
    description: 'Reliable grip for both tarmac and soft terrain. Built for the long haul on Pakistani roads.',
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Suzuki Pakistan', 'United'], models: ['CG 125', 'GS 150', 'US 70'], years: [2000, 2024] },
    rating: 4.9,
    reviewCount: 1102
  },
  {
    id: 'p9',
    name: 'Chrome Performance Downpipe (Honda CG 125)',
    price: 4500,
    type: 'Bike',
    category: 'PERFORMANCE',
    description: 'High-flow exhaust downpipe for improved engine breathing and a deeper bass exhaust note.',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda'], models: ['CG 125'], years: [2005, 2024] },
    rating: 4.6,
    reviewCount: 184
  },
  {
    id: 'p10',
    name: 'Formula 1 Scratch Out & Polish Wax',
    price: 1650,
    type: 'Universal',
    category: 'CAR CARE',
    description: 'Removes fine scratches and swirl marks while providing a brilliant Carnauba wax shine.',
    image: 'https://images.unsplash.com/photo-1520333789090-1afc82db536a?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Kia', 'MG'] },
    rating: 4.5,
    reviewCount: 310
  },
  {
    id: 'p11',
    name: 'Universal Car Shark Fin Antenna (Integrated Signal Booster)',
    price: 1450,
    type: 'Car',
    category: 'EXTERIOR',
    description: 'Sleek aerodynamic design that replaces your standard antenna. Improves radio signal and look.',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Kia', 'Changan'], models: ['Civic', 'Corolla', 'Alto', 'Sportage', 'Alsvin'] },
    rating: 4.6,
    reviewCount: 78
  },
  {
    id: 'p12',
    name: 'Car Interior Ambience Lighting (App Controlled)',
    price: 4800,
    type: 'Car',
    category: 'INTERIOR',
    description: 'Color-changing RGB LED strips for your car footwell and dashboard. Control via smartphone app.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Kia', 'MG'] },
    rating: 4.9,
    reviewCount: 142
  },
  {
    id: 'p13',
    name: 'Universal Bike Lava Indicators – Audi & Eye Style (Set of 2)',
    price: 1250,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Distinctive Eye-style LED indicators with sequential Audi-style flowing effect.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha'], models: ['CG 125', 'YBR 125'], years: [2010, 2024] },
    rating: 4.7,
    reviewCount: 95
  },
  {
    id: 'p14',
    name: 'HJG Mini Driving Fog Lights (Dual Color White/Yellow)',
    price: 3200,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Compact high-powered fog lights. Ideal for nighttime touring and foggy conditions.',
    image: 'https://images.unsplash.com/photo-1594976614436-ecf130b050cf?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Suzuki Pakistan', 'Yamaha'], years: [2015, 2024] },
    rating: 4.9,
    reviewCount: 210,
    featured: true
  },
  {
    id: 'p15',
    name: 'Bike Lava Smoke Z-Shape Indicators (2 Pcs Set)',
    price: 1100,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Unique Z-shaped sequential LED indicators with a smoked lens for a stealthy look.',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha'], models: ['CG 125', 'YBR 125'], years: [2010, 2024] },
    rating: 4.6,
    reviewCount: 54
  },
  {
    id: 'p16',
    name: 'Universal Side Mirror Indicators (Black Pair)',
    price: 2450,
    type: 'Bike',
    category: 'MODIFICATIONS',
    description: 'Integrated blinkers inside the mirrors for better visibility to oncoming traffic.',
    image: 'https://images.unsplash.com/photo-1558981850-d73241662719?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Suzuki Pakistan'], models: ['CB 150F', 'GS 150'], years: [2017, 2024] },
    rating: 4.8,
    reviewCount: 37
  },
  {
    id: 'p18',
    name: 'Bullet Style LED Indicators (Yellow Pair)',
    price: 850,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Classic bullet shaped indicators with bright amber LEDs. Durable metal housing.',
    image: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf815?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha'], models: ['CG 125', 'YBR 125'], years: [2000, 2024] },
    rating: 4.4,
    reviewCount: 88
  },
  {
    id: 'p19',
    name: 'Owl Shape HJG Auxiliary Lights (Set of 2)',
    price: 4500,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Distinctive owl-eye design auxiliary lights. Extremely bright beam with strobe mode.',
    image: 'https://images.unsplash.com/photo-1558980335-8e0c25ad75de?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Suzuki Pakistan', 'Yamaha'], models: ['CB 150F', 'GS 150', 'YBR 125G'], years: [2010, 2024] },
    rating: 5.0,
    reviewCount: 15
  },
  {
    id: 'p20',
    name: 'Bike Smoke LAVA U-Style Indicators',
    price: 1350,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'U-shaped LED indicators with a smoked finish. Flowing animation for a modern look.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha'], models: ['CG 125', 'YBR 125'], years: [2010, 2024] },
    rating: 4.7,
    reviewCount: 42
  },
  {
    id: 'p21',
    name: 'Honda Civic X Ducktail Spoiler (Carbon Fiber Finish)',
    price: 8500,
    type: 'Car',
    category: 'EXTERIOR',
    description: 'Aero ducktail spoiler for Civic 2016-2021. Sporty look with high quality finish.',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda'], models: ['Civic'], years: [2016, 2021] },
    rating: 4.8,
    reviewCount: 22
  },
  {
    id: 'p22',
    name: 'Toyota Corolla Altis Grande Floor Mats (5D Diamond)',
    price: 6400,
    type: 'Car',
    category: 'CAR MATS',
    description: 'Custom fit waterproof diamond design floor mats. Easy to clean and extremely durable.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Toyota'], models: ['Corolla'], years: [2014, 2024] },
    rating: 4.9,
    reviewCount: 115
  },
  {
    id: 'p23',
    name: 'Yamaha YBR 125 Sporty Seat Cover (Anti-Slip)',
    price: 1400,
    type: 'Bike',
    category: 'MODIFICATIONS',
    description: 'High-grip seat cover with red stitching. Protects original seat and improves riding posture.',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Yamaha'], models: ['YBR 125', 'YBR 125G'], years: [2015, 2024] },
    rating: 4.5,
    reviewCount: 67
  },
  {
    id: 'p24',
    name: 'Universal Car GPS Tracker (Live Tracking)',
    price: 3500,
    type: 'Universal',
    category: 'SECURITY GADGETS',
    description: 'Real-time tracking for your vehicle. Mobile app alerts for engine start and geo-fencing.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Kia', 'MG'] },
    rating: 4.7,
    reviewCount: 210
  },
  {
    id: 'p25',
    name: 'HJG Fog Light Wiring Harness with Relay',
    price: 1200,
    type: 'Bike',
    category: 'MODIFICATIONS',
    description: 'Complete wiring kit for auxiliary lights. Includes 12V 40A relay and waterproof switch.',
    image: 'https://images.unsplash.com/photo-1594976614436-ecf130b050cf?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'] },
    rating: 4.6,
    reviewCount: 38
  },
  {
    id: 'p26',
    name: 'Car Windshield Sun Shade (Foldable)',
    price: 1100,
    type: 'Car',
    category: 'EXTERIOR',
    description: 'Protects car interior from harsh UV rays. Keeps your cabin cool in summer.',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Changan'] },
    rating: 4.3,
    reviewCount: 156
  },
  {
    id: 'p27',
    name: 'High Intensity H4 LED Headlight Bulbs',
    price: 3800,
    type: 'Universal',
    category: 'LED & LIGHTNING',
    description: 'Direct replacement for halogen bulbs. 6000K daylight white with focused beam pattern.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Kia', 'Yamaha'] },
    rating: 4.8,
    reviewCount: 89
  },
  {
    id: 'p28',
    name: 'Motorcycle Saddle Bags (Waterproof Pair)',
    price: 5500,
    type: 'Bike',
    category: 'JEEP, SUV & BIKE',
    description: 'Heavy duty touring saddle bags. Expandable storage with multiple compartments.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan', 'Kawasaki'] },
    rating: 4.7,
    reviewCount: 34
  },
  {
    id: 'p29',
    name: 'Car Dashboard Polish (Premium Shine)',
    price: 750,
    type: 'Car',
    category: 'CAR CARE',
    description: 'Protects dashboard from fading. Non-greasy formula with fresh fragrance.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Kia'] },
    rating: 4.5,
    reviewCount: 220
  },
  {
    id: 'p30',
    name: 'Universal Car Steering Wheel Cover (Mesh)',
    price: 1250,
    type: 'Car',
    category: 'INTERIOR',
    description: 'Breathable mesh material for better grip. Universal size fits most cars.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Changan'] },
    rating: 4.2,
    reviewCount: 92
  },
  {
    id: 'p31',
    name: 'Bike Chain Lube (High Speed Formula)',
    price: 950,
    type: 'Bike',
    category: 'CAR CARE',
    description: 'Synthetic chain lubricant for motorcycles. Reduces friction and prevents rust.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'] },
    rating: 4.9,
    reviewCount: 180
  },
  {
    id: 'p32',
    name: 'Android Panel for City 2009-2021 (9 Inch)',
    price: 14500,
    type: 'Car',
    category: 'MUSIC & STEREO',
    description: 'High definition touch screen with Apple CarPlay and Android Auto support.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda'], models: ['City'], years: [2009, 2021] },
    rating: 4.8,
    reviewCount: 45
  },
  {
    id: 'p33',
    name: 'Universal Car Paint Protection Film (DIY Kit)',
    price: 2800,
    type: 'Universal',
    category: 'PAINT PROTECTION',
    description: 'Transparent film to protect door edges and handles from scratches.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Kia'] },
    rating: 4.4,
    reviewCount: 76
  },
  {
    id: 'p34',
    name: 'Motorcycle Disc Brake Fluid (DOT 4)',
    price: 650,
    type: 'Bike',
    category: 'CAR CARE',
    description: 'High performance brake fluid for hydraulic disc brakes.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'] },
    rating: 4.7,
    reviewCount: 120
  },
  {
    id: 'p35',
    name: 'Universal Car Bluetooth FM Transmitter',
    price: 1800,
    type: 'Universal',
    category: 'GADGETS',
    description: 'Stream music and take calls via your car radio. Includes fast USB charging ports.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Changan'] },
    rating: 4.6,
    reviewCount: 144
  },
  {
    id: 'p36',
    name: 'Heavy Duty Bike Guard with Footrests',
    price: 3200,
    type: 'Bike',
    category: 'MODIFICATIONS',
    description: 'Protective crash guard with comfortable footrests for long rides.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda'], models: ['CG 125', 'CB 150F'], years: [2010, 2024] },
    rating: 4.8,
    reviewCount: 29,
    featured: true
  },
  {
    id: 'p37',
    name: 'Car Tire Pressure Monitoring System (Solar)',
    price: 4800,
    type: 'Car',
    category: 'SECURITY GADGETS',
    description: 'Solar powered TPMS with 4 external sensors for real-time pressure monitoring.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Toyota', 'Suzuki', 'Kia'] },
    rating: 4.7,
    reviewCount: 58
  },
  {
    id: 'p38',
    name: '6 SMD Motorcycle Police Flasher Emergency Light (Red/Blue 12V)',
    price: 1200,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Ultra-bright 6-LED emergency strobe for motorcycles. Compact and weather-resistant.',
    image: 'https://images.unsplash.com/photo-1557597774-9d2739f05a76?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'], years: [2010, 2024] },
    rating: 4.6,
    reviewCount: 92
  },
  {
    id: 'p39',
    name: 'High-Powered LED Motorcycle Fog Light – Durable & Waterproof',
    price: 1150,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Focused beam projection for enhanced safety in fog and low light. Aluminum body for cooling.',
    image: 'https://images.unsplash.com/photo-1594976614436-ecf130b050cf?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Suzuki Pakistan'], models: ['CG 125', 'GS 150'], years: [2015, 2024] },
    rating: 4.7,
    reviewCount: 31
  },
  {
    id: 'p40',
    name: 'MOXI Bike Side Indicators – Sleek Line Style (Pair)',
    price: 1050,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Sleek horizontal line-style LEDs with smoked lenses. Discrete yet highly visible.',
    image: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf815?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Yamaha', 'Suzuki Pakistan'], models: ['YBR 125G', 'GR 150'], years: [2017, 2024] },
    rating: 4.5,
    reviewCount: 18
  },
  {
    id: 'p42',
    name: '48 SMD Motorcycle Flasher Light (Red Blue 12V)',
    price: 2800,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Extreme intensity 48-SMD emergency flasher. Multiple strobe patterns with high-profile visibility.',
    image: 'https://images.unsplash.com/photo-1557597774-9d2739f05a76?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'], years: [2010, 2024] },
    rating: 4.9,
    reviewCount: 34
  },
  {
    id: 'p43',
    name: '24 LED Motorcycle Flasher Light (Red Blue 12V)',
    price: 1950,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'High visibility 24-LED emergency warning light. Durable and energy efficient for 12V systems.',
    image: 'https://images.unsplash.com/photo-1557597774-9d2739f05a76?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'], years: [2010, 2024] },
    rating: 4.7,
    reviewCount: 52
  },
  {
    id: 'p44',
    name: 'Turn Signal Blinker & Brake Lights (Set of 4)',
    price: 3500,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: '12 LED 3-wire multifunction lights. Functions as both indicators and auxiliary brake lights. Black finish.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'], models: ['CB 150F', 'YBR 125G', 'GS 150'], years: [2015, 2024] },
    rating: 4.8,
    reviewCount: 26
  },
  {
    id: 'p45',
    name: 'Motorcycle Front Flasher Light Without Host (Red Blue 12V)',
    price: 1500,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Direct-wire emergency flasher module. bright red and blue strobe effect for front mounting.',
    image: 'https://images.unsplash.com/photo-1557597774-9d2739f05a76?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'], years: [2010, 2024] },
    rating: 4.5,
    reviewCount: 41
  },
  {
    id: 'p46',
    name: 'Police Motorcycle LED Warning Emergency Lights (Lava Style)',
    price: 2200,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'Triangular lava-style emergency lights. Intense red/blue dual color warning system.',
    image: 'https://images.unsplash.com/photo-1557597774-9d2739f05a76?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'], years: [2015, 2024] },
    rating: 4.8,
    reviewCount: 19
  },
  {
    id: 'p47',
    name: 'High Performance Racing Air Filter (Honda CG 125)',
    price: 1800,
    type: 'Bike',
    category: 'PERFORMANCE',
    description: 'Increases air flow for better combustion and throttle response. Washable and reusable.',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda'], models: ['CG 125', 'CB 150F'], years: [2000, 2024] },
    rating: 4.9,
    reviewCount: 156
  },
  {
    id: 'p48',
    name: 'Black Alloy Rim Set for CD 70 (Front & Rear)',
    price: 12500,
    type: 'Bike',
    category: 'WHEEL & RIMS',
    description: 'Lightweight and durable alloy rims. drastically improves the look and handling of your bike.',
    image: 'https://images.unsplash.com/photo-1611095777215-99bb5c083bc3?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'United'], models: ['CD 70', 'US 70'], years: [2010, 2024] },
    rating: 4.7,
    reviewCount: 42
  },
  {
    id: 'p49',
    name: 'HID Projector Headlight Assembly for Civic (2016-2021)',
    price: 15000,
    type: 'Car',
    category: 'LED & LIGHTNING',
    description: 'Crystal clear projector lens with high-intensity HID bulbs. Dramatic improvement in nighttime visibility.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda'], models: ['Civic'], years: [2016, 2021] },
    rating: 4.9,
    reviewCount: 28
  },
  {
    id: 'p50',
    name: 'Premium Ceramic Brake Pads for Kia Sportage',
    price: 8500,
    type: 'Car',
    category: 'PERFORMANCE',
    description: 'Low-dust, noise-free ceramic brake pads. Superior stopping power and rotor protection.',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Kia'], models: ['Sportage'], years: [2019, 2024] },
    rating: 5.0,
    reviewCount: 14
  },
  {
    id: 'p51',
    name: 'Carbon Fiber Style Mirror Covers for Corolla',
    price: 4200,
    type: 'Car',
    category: 'EXTERIOR',
    description: 'Clip-on ABS plastic covers with premium carbon fiber dip finish. Aggressive sporty look.',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Toyota'], models: ['Corolla'], years: [2014, 2024] },
    rating: 4.6,
    reviewCount: 31
  },
  {
    id: 'p52',
    name: 'Bike LED Tail Light with Integrated Indicators',
    price: 2600,
    type: 'Bike',
    category: 'LED & LIGHTNING',
    description: 'All-in-one rear lighting solution. Bright brake light with amber sequential turn signals.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha'], models: ['CG 125', 'YBR 125'], years: [2015, 2024] },
    rating: 4.8,
    reviewCount: 89
  },
  {
    id: 'p53',
    name: 'Motorcycle Handguards with Integrated LED DRLs',
    price: 2900,
    type: 'Bike',
    category: 'MODIFICATIONS',
    description: 'Protects hands from wind and debris. Built-in white LEDs for added presence on the road.',
    image: 'https://images.unsplash.com/photo-1558981424-8fed39710e3d?auto=format&fit=crop&q=80&w=800',
    fitment: { brands: ['Honda', 'Yamaha', 'Suzuki Pakistan'], models: ['CB 150F', 'YBR 125G', 'GS 150'], years: [2010, 2024] },
    rating: 4.7,
    reviewCount: 45
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    userName: 'Kashif Ali',
    rating: 5,
    comment: 'The running indicators look amazing on my YBR. Very premium feel and fast delivery to Karachi.',
    date: '2024-04-12',
    vehicle: '2022 Yamaha YBR 125'
  },
  {
    id: 'r2',
    userName: 'Zubair Shah',
    rating: 5,
    comment: 'Installed the Android panel in my Civic today. The IPS display is crystal clear and sound quality improved significantly.',
    date: '2024-03-22',
    vehicle: '2023 Honda Civic'
  },
  {
    id: 'r3',
    userName: 'Osama Bin Tariq',
    rating: 4,
    comment: 'Panther tires are best for local roads. Good grip even in rain. Highly recommend MOTOFIT!',
    date: '2024-02-10',
    vehicle: '2021 Honda CG 125'
  }
];
